// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import './config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbnlXRYGlJgdWQsIIIqYTSTg2rE2A7WI',
    appId: '1:1063682545509:android:1828ffe8f52402250b338c',
    messagingSenderId: '1063682545509',
    projectId: 't-zens',
    databaseURL: 'https://t-zens-default-rtdb.firebaseio.com',
    storageBucket: 't-zens.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIJfn2537CrmfeTlS9ljNtj-3bHju7R4',
    appId: '1:1063682545509:web:e5f91f3943c5f4a10b338c',
    messagingSenderId: '1063682545509',
    projectId: 't-zens',
    authDomain: 't-zens.firebaseapp.com',
    databaseURL: 'https://t-zens-default-rtdb.firebaseio.com',
    storageBucket: 't-zens.appspot.com',
    measurementId: 'G-B7QXYTRKQW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvMrkYMFsv3gzsMlvI88xc50605P_JsA',
    appId: '1:1063682545509:ios:2bff0ddca44d716c0b338c',
    messagingSenderId: '1063682545509',
    projectId: 't-zens',
    databaseURL: 'https://t-zens-default-rtdb.firebaseio.com',
    storageBucket: 't-zens.appspot.com',
    androidClientId: '1063682545509-9jrpue91euhq3l3l0s829jf3busc06ku.apps.googleusercontent.com',
    iosClientId: '1063682545509-03n25mesleg12414rl4nuve2bamgr90v.apps.googleusercontent.com',
    iosBundleId: 'com.ngeureuyeuh.tzens',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvMrkYMFsv3gzsMlvI88xc50605P_JsA',
    appId: '1:1063682545509:ios:2bff0ddca44d716c0b338c',
    messagingSenderId: '1063682545509',
    projectId: 't-zens',
    databaseURL: 'https://t-zens-default-rtdb.firebaseio.com',
    storageBucket: 't-zens.appspot.com',
    androidClientId: '1063682545509-9jrpue91euhq3l3l0s829jf3busc06ku.apps.googleusercontent.com',
    iosClientId: '1063682545509-03n25mesleg12414rl4nuve2bamgr90v.apps.googleusercontent.com',
    iosBundleId: 'com.ngeureuyeuh.tzens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrIWFCngwfEgGf0D1JD9oJpTKWJAr61zc',
    appId: '1:1063682545509:web:dd5591529c600f620b338c',
    messagingSenderId: '1063682545509',
    projectId: 't-zens',
    authDomain: 't-zens.firebaseapp.com',
    databaseURL: 'https://t-zens-default-rtdb.firebaseio.com',
    storageBucket: 't-zens.appspot.com',
    measurementId: 'G-03LLMVQMJJ',
  );

}